### ISSUE TITLE
not really usable

### ISSUE THREAD

**Issue by adamscottv** [EGjoni/Everything-WIll-Be-IK#1]
It's too bad the underlying Java implementation is dependent on classes like pseudoScene.DVector. As far as I can tell, none of this code will work outside of sketchbook. Are you planning to release the source and make it standalone Java?

**Comment by EGjoni** [comment]
Yeah, I plan to modify the source to be less coupled to processing in a few weeks.

In the meantime, it'll work fine outside of sketchbook so long as your project imports the processing core libs.

**Comment by adamscottv** [comment]
Thanks for the response. I was able to get DVector to compile by adding processing's core.jar. I'll play with it and see what kind of results I can get.

I wish source was attached to the jar... [😊]

**Comment by EGjoni** [comment]
Excellent. Please note I've just added a disclaimer to the readme that might be relevant to your use case and plan accordingly. 

I will be updating the library soon to minimize potential issues. But if you note any wonky behaviors, please let me know.
