### ISSUE TITLE
NullPointerException when calling getPin if enablePin was not called.

### ISSUE THREAD

**Issue by adamscottv** [EGjoni/Everything-WIll-Be-IK#3]
To reproduce, construct a new Bone, then call bone.getPin(). A NPE will result. Then add bone.enablePin() before getPin(), and it returns a DVector. If the pin is not enabled, it should probably just return null and not error out.

**Comment by EGjoni** [comment]
Okay. Should be fixed now.

**Comment by adamscottv** [comment]
Cool.
